# // docker compose -f docker-compose.prod.yml up
# // docker tag expressjs-react-server 1221jyp/luton:latest
# // docker push 1221jyp/luton:latest
# // docker buildx build --platform linux/amd64,linux/arm64 -t 1221jyp/luton:latest .
# // docker compose build --platform linux/amd64,linux/arm64 --no-cache
# // DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose build

# 프로덕션 환경에서는 npm start로 실행되고 구글 로그인 리다이렉트 주소가 바뀜.
# 개발 환경에서 프로덕션 환경 실행시, 사이트는 정상 작동하는것을 확인할 수 있으나, 구글 로그인이 안되어야 하는데,
# ?? localhost로 접속해서 구글 로그인하면 1uton.com으로 리다이렉트가 된다. ??
# 상관은 없을거같다.

#docker-compose.prod.yml
#프로덕션 환경 구성

version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production
    command: npm start # ✅ 프로덕션에서는 `nodemon` 없이 실행
    volumes:
      - ./client/build:/app/build # ✅ React 빌드 결과를 서버에서 서빙
